nmr = int(input('- Digite o número que deseja ver a tabuada: '))
print('Segue a tabuada do número', nmr)
print('{} x {:2} = {}'.format(nmr, 1, nmr*1))
print('{} x {:2} = {}'.format(nmr, 2, nmr*2))
print('{} x {:2} = {}'.format(nmr, 3, nmr*3))
print('{} x {:2} = {}'.format(nmr, 4, nmr*4))
print('{} x {:2} = {}'.format(nmr, 5, nmr*5))
print('{} x {:2} = {}'.format(nmr, 6, nmr*6))
print('{} x {:2} = {}'.format(nmr, 7, nmr*7))
print('{} x {:2} = {}'.format(nmr, 8, nmr*8))
print('{} x {:2} = {}'.format(nmr, 9, nmr*9))
print('{} x {:2} = {}'.format(nmr,10, nmr*10))
print('_'* 20)

